name: Node.js Patch Release

on:
  push:
    branches:
      - release/patch

jobs:
  publish_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NODE_ENV: development
      - run: git config --global user.email "makame@mail.ru"
      - run: git config --global user.name "CICD"
      - run: git fetch origin
      - run: git checkout -b release-patch origin/release/patch
      - run: git pull origin release/patch --allow-unrelated-histories
      - run: git merge origin release/patch
      - run: git checkout -b release-master origin/master
      - run: git pull origin master --allow-unrelated-histories
      - run: git merge origin master
      - run: git merge release-patch
      - run: npm run release:patch
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN_CICD}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
