name: Node.js Patch Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - '.github/**'

jobs:
  publish_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NODE_ENV: development
      - run: git config --global user.email "makame@mail.ru"
      - run: git config --global user.name "CICD"
      - name: Temporarily disable "include administrators" branch protection
        uses: makamekm/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN_CICD }}
      - run: npm run release:patch
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN_CICD}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Enable "include administrators" branch protection
        uses: makamekm/branch-protection-bot@master
        if: always()  # Force to always run this step to ensure "include administrators" is always turned back on
        with:
          access-token: ${{ secrets.GITHUB_TOKEN_CICD }}
          owner: benjefferies
          repo: branch-protection-bot
