name: Node.js Major Release

on:
  push:
    branches:
      - release/major

jobs:
  publish_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NODE_ENV: development
      - run: git config --global user.email "makame@mail.ru"
      - run: git config --global user.name "CICD"
      - run: git fetch origin
      - run: git checkout -b master origin/master
      - run: git merge release/major
      - name: Temporarily disable "include administrators" branch protection
        uses: makamekm/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN_CICD }}
          enforce_admins: false
      - run: npm run release:major
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN_CICD}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Enable "include administrators" branch protection
        uses: makamekm/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN_CICD }}
          enforce_admins: true
