name: Node.js Patch Release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'

jobs:
  publish_patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NODE_ENV: development
      - run: npm run release:patch
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

