name: Node.js Develop Test

on:
  push:
    branches:
      - develop

jobs:
  test_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
        env:
          NODE_ENV: development
      - run: npm run lint
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name : GITHUB CONTEXT
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }} 
        run: echo "$GITHUB_CONTEXT" 
      - name: get commit message
        run: echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run : echo $commitmsg
      - name: send a success message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Figma React - ${{ github.ref }}
            SUCCESSFULLY - test
            Triggered by ${{ github.event_name }} event
            https://github.com/makamekm/figma-react/actions/runs/${{ github.run_id }}
            ${{ commitmsg }}
      - name: send a fail message
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Figma React - ${{ github.ref }}
            FAILED - test
            Triggered by ${{ github.event_name }} event
            https://github.com/makamekm/figma-react/actions/runs/${{ github.run_id }}
            ${{ commitmsg }}
