name: Node.js Public Release Notes

on:
  release:
      types:
        - created

jobs:
  test_develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Log context
        uses: actions/github-script@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log(context.payload);
      - name: Extract tag name
        id: tag
        uses: actions/github-script@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            return context.payload.release.tag_name;
      - name: send release notes
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_PUBLIC_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            New version of Figma React ${{ steps.tag.outputs.result }} has been released
            https://github.com/makamekm/figma-react/releases/tag/${{ steps.tag.outputs.result }}
            https://www.npmjs.com/package/figma-react
